### ISSUE TITLE
ActionBar, Title

### ISSUE THREAD

**Issue by UnixPL** [KawaiiGuilds/KawaiiGuilds#1]
W tym pluginie jest wyświetlanie wiadomości na actionbar oraz title?

**Comment by 3nzxhsq** [comment]
Niestety plugin posiada dopiero podstawowy zarys kodu/funkcji i nic więcej. Planujemy skończyć go w następny tydzień, ale raczej znajdzie się w nim możliwość wysyłania wiadomości przez actionbar lub title(do wyboru w configu).

**Comment by UnixPL** [comment]
Hm, a wersja pluginu jaka jest teraz pozostanie czy będzie można dobrać pod swój serwer?

**Comment by 3nzxhsq** [comment]
Na razie wszystko jest testowane na 1.12, ale planujemy dodać wsparcie 1.8 - 1.12

**Comment by UnixPL** [comment]
To powodzenia!
